/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SurveySurveyIdRouteImport } from './routes/survey/$surveyId'
import { Route as DashboardResponsesRouteImport } from './routes/dashboard/responses'
import { Route as DashboardBuilderRouteImport } from './routes/dashboard/builder'
import { Route as DashboardBrandingRouteImport } from './routes/dashboard/branding'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardIndexNewRouteImport } from './routes/dashboard/index.new'
import { Route as DashboardSurveyIdResponsesRouteImport } from './routes/dashboard/$surveyId/responses'
import { Route as DashboardSurveyIdBuilderRouteImport } from './routes/dashboard/$surveyId/builder'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveySurveyIdRoute = SurveySurveyIdRouteImport.update({
  id: '/survey/$surveyId',
  path: '/survey/$surveyId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardResponsesRoute = DashboardResponsesRouteImport.update({
  id: '/dashboard/responses',
  path: '/dashboard/responses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBuilderRoute = DashboardBuilderRouteImport.update({
  id: '/dashboard/builder',
  path: '/dashboard/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBrandingRoute = DashboardBrandingRouteImport.update({
  id: '/dashboard/branding',
  path: '/dashboard/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexNewRoute = DashboardIndexNewRouteImport.update({
  id: '/dashboard/index/new',
  path: '/dashboard/index/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSurveyIdResponsesRoute =
  DashboardSurveyIdResponsesRouteImport.update({
    id: '/dashboard/$surveyId/responses',
    path: '/dashboard/$surveyId/responses',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSurveyIdBuilderRoute =
  DashboardSurveyIdBuilderRouteImport.update({
    id: '/dashboard/$surveyId/builder',
    path: '/dashboard/$surveyId/builder',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/branding': typeof DashboardBrandingRoute
  '/dashboard/builder': typeof DashboardBuilderRoute
  '/dashboard/responses': typeof DashboardResponsesRoute
  '/survey/$surveyId': typeof SurveySurveyIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$surveyId/builder': typeof DashboardSurveyIdBuilderRoute
  '/dashboard/$surveyId/responses': typeof DashboardSurveyIdResponsesRoute
  '/dashboard/index/new': typeof DashboardIndexNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/branding': typeof DashboardBrandingRoute
  '/dashboard/builder': typeof DashboardBuilderRoute
  '/dashboard/responses': typeof DashboardResponsesRoute
  '/survey/$surveyId': typeof SurveySurveyIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$surveyId/builder': typeof DashboardSurveyIdBuilderRoute
  '/dashboard/$surveyId/responses': typeof DashboardSurveyIdResponsesRoute
  '/dashboard/index/new': typeof DashboardIndexNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/branding': typeof DashboardBrandingRoute
  '/dashboard/builder': typeof DashboardBuilderRoute
  '/dashboard/responses': typeof DashboardResponsesRoute
  '/survey/$surveyId': typeof SurveySurveyIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$surveyId/builder': typeof DashboardSurveyIdBuilderRoute
  '/dashboard/$surveyId/responses': typeof DashboardSurveyIdResponsesRoute
  '/dashboard/index/new': typeof DashboardIndexNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/branding'
    | '/dashboard/builder'
    | '/dashboard/responses'
    | '/survey/$surveyId'
    | '/dashboard/'
    | '/dashboard/$surveyId/builder'
    | '/dashboard/$surveyId/responses'
    | '/dashboard/index/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/branding'
    | '/dashboard/builder'
    | '/dashboard/responses'
    | '/survey/$surveyId'
    | '/dashboard'
    | '/dashboard/$surveyId/builder'
    | '/dashboard/$surveyId/responses'
    | '/dashboard/index/new'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/branding'
    | '/dashboard/builder'
    | '/dashboard/responses'
    | '/survey/$surveyId'
    | '/dashboard/'
    | '/dashboard/$surveyId/builder'
    | '/dashboard/$surveyId/responses'
    | '/dashboard/index/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  DashboardBrandingRoute: typeof DashboardBrandingRoute
  DashboardBuilderRoute: typeof DashboardBuilderRoute
  DashboardResponsesRoute: typeof DashboardResponsesRoute
  SurveySurveyIdRoute: typeof SurveySurveyIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSurveyIdBuilderRoute: typeof DashboardSurveyIdBuilderRoute
  DashboardSurveyIdResponsesRoute: typeof DashboardSurveyIdResponsesRoute
  DashboardIndexNewRoute: typeof DashboardIndexNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey/$surveyId': {
      id: '/survey/$surveyId'
      path: '/survey/$surveyId'
      fullPath: '/survey/$surveyId'
      preLoaderRoute: typeof SurveySurveyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/responses': {
      id: '/dashboard/responses'
      path: '/dashboard/responses'
      fullPath: '/dashboard/responses'
      preLoaderRoute: typeof DashboardResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/builder': {
      id: '/dashboard/builder'
      path: '/dashboard/builder'
      fullPath: '/dashboard/builder'
      preLoaderRoute: typeof DashboardBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/branding': {
      id: '/dashboard/branding'
      path: '/dashboard/branding'
      fullPath: '/dashboard/branding'
      preLoaderRoute: typeof DashboardBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/index/new': {
      id: '/dashboard/index/new'
      path: '/dashboard/index/new'
      fullPath: '/dashboard/index/new'
      preLoaderRoute: typeof DashboardIndexNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$surveyId/responses': {
      id: '/dashboard/$surveyId/responses'
      path: '/dashboard/$surveyId/responses'
      fullPath: '/dashboard/$surveyId/responses'
      preLoaderRoute: typeof DashboardSurveyIdResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$surveyId/builder': {
      id: '/dashboard/$surveyId/builder'
      path: '/dashboard/$surveyId/builder'
      fullPath: '/dashboard/$surveyId/builder'
      preLoaderRoute: typeof DashboardSurveyIdBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  DashboardBrandingRoute: DashboardBrandingRoute,
  DashboardBuilderRoute: DashboardBuilderRoute,
  DashboardResponsesRoute: DashboardResponsesRoute,
  SurveySurveyIdRoute: SurveySurveyIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSurveyIdBuilderRoute: DashboardSurveyIdBuilderRoute,
  DashboardSurveyIdResponsesRoute: DashboardSurveyIdResponsesRoute,
  DashboardIndexNewRoute: DashboardIndexNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
